apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vkcuj9d8i-java-quarkus
  janus-idp.io/tekton: vkcuj9d8i-java-quarkus
  backstage.io/kubernetes-id: vkcuj9d8i-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vkcuj9d8i-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
